#!/usr/bin/env python3
"""
update_financial_targets_from_csv.py
-------------------------------------
Updates llm_V1/financial_targets.json with certificate hashes from the CSV
file generated by extract_app_certificates.ps1

Usage:
    python scripts/update_financial_targets_from_csv.py financial_app_certificates.csv
"""

import argparse
import csv
import json
import os
import sys
from typing import Dict, List


def load_csv_certificates(csv_path: str) -> Dict[str, Dict[str, str]]:
    """Load certificate data from CSV into a dictionary keyed by package name."""
    certs = {}
    
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            package = row.get('Package_Name', '').strip()
            sha1 = row.get('SHA1', '').strip()
            sha256 = row.get('SHA256', '').strip()
            
            if package and sha1 and sha256:
                certs[package] = {
                    'sha1': sha1,
                    'sha256': sha256,
                    'app_name': row.get('App_Name', ''),
                    'category': row.get('Category', ''),
                }
    
    return certs


def update_financial_targets(json_path: str, cert_data: Dict[str, Dict[str, str]], dry_run: bool = False):
    """Update financial_targets.json with certificate hashes."""
    
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    updated_count = 0
    added_count = 0
    
    for target in data.get('targets', []):
        for official_app in target.get('official_apps', []):
            package_name = official_app.get('package_name', '')
            
            if package_name in cert_data:
                cert_info = cert_data[package_name]
                
                # Get existing certs
                existing_sha1 = official_app.get('cert_sha1', [])
                existing_sha256 = official_app.get('cert_sha256', [])
                
                # Check if cert already exists
                new_sha1 = cert_info['sha1']
                new_sha256 = cert_info['sha256']
                
                if new_sha1 not in existing_sha1:
                    existing_sha1.append(new_sha1)
                    official_app['cert_sha1'] = existing_sha1
                    added_count += 1
                    print(f"[+] Added SHA-1 for {package_name}")
                
                if new_sha256 not in existing_sha256:
                    existing_sha256.append(new_sha256)
                    official_app['cert_sha256'] = existing_sha256
                    print(f"[+] Added SHA-256 for {package_name}")
                
                updated_count += 1
    
    if not dry_run:
        # Backup original file
        backup_path = json_path + '.backup'
        if os.path.exists(backup_path):
            print(f"[!] Backup already exists: {backup_path}")
        else:
            with open(backup_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
            print(f"[*] Created backup: {backup_path}")
        
        # Write updated JSON
        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        
        print(f"\n[+] Updated {json_path}")
        print(f"    - Packages updated: {updated_count}")
        print(f"    - Certificates added: {added_count}")
    else:
        print(f"\n[*] DRY RUN - No changes made")
        print(f"    - Would update {updated_count} packages")
        print(f"    - Would add {added_count} certificates")


def main():
    parser = argparse.ArgumentParser(
        description='Update financial_targets.json with certificates from CSV'
    )
    parser.add_argument(
        'csv_file',
        help='CSV file containing certificate data (from extract_app_certificates.ps1)'
    )
    parser.add_argument(
        '--json',
        default='llm_V1/financial_targets.json',
        help='Path to financial_targets.json (default: llm_V1/financial_targets.json)'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Show what would be changed without actually updating the file'
    )
    
    args = parser.parse_args()
    
    # Validate inputs
    if not os.path.exists(args.csv_file):
        print(f"[-] CSV file not found: {args.csv_file}", file=sys.stderr)
        return 1
    
    if not os.path.exists(args.json):
        print(f"[-] JSON file not found: {args.json}", file=sys.stderr)
        return 1
    
    print("=" * 80)
    print("  Update Financial Targets with Certificate Baselines")
    print("=" * 80)
    print()
    print(f"CSV Input:  {args.csv_file}")
    print(f"JSON File:  {args.json}")
    print(f"Dry Run:    {args.dry_run}")
    print()
    
    # Load certificates from CSV
    print("[*] Loading certificate data from CSV...")
    cert_data = load_csv_certificates(args.csv_file)
    print(f"[+] Loaded {len(cert_data)} certificate entries")
    print()
    
    # Update JSON
    print("[*] Updating financial_targets.json...")
    update_financial_targets(args.json, cert_data, dry_run=args.dry_run)
    print()
    
    if not args.dry_run:
        print("[+] Update complete!")
        print()
        print("Next steps:")
        print("1. Review the changes in llm_V1/financial_targets.json")
        print("2. Test certificate verification with a known-good APK")
        print("3. If issues occur, restore from backup: llm_V1/financial_targets.json.backup")
    else:
        print("[*] Run without --dry-run to apply changes")
    
    print()
    print("=" * 80)
    print()
    
    return 0


if __name__ == '__main__':
    sys.exit(main())
